- name: Install packages, reboot and clean cache
  become: true
  hosts: buildbots

  tasks:
    - name: Update all packages
      package:
        name: '*'
        state: latest

    - name: check if reboot is needed
      command: "dnf needs-restarting -r -s"
      register: needs_restarting
      changed_when: needs_restarting.rc == 1
      failed_when: false
      notify: Reboot after update

    - name: Clean the dnf cache
      command: dnf clean all

  handlers:
    - name: Reboot after update
      reboot:

- name: Clean the systemd logs
  gather_facts: no
  hosts: buildbots

  tasks:
    - name: clean logs older than 30 days
      command: journalctl --vacuum-time=30d
      changed_when: False

- name: Clean disk space
  gather_facts: no
  hosts: buildbots
  become: true

  tasks:
    - name: Discover buildbot worker service name
      shell: systemctl list-units --type=service --all --plain --no-legend 'buildbot-worker@*.service' | awk '{print $1}' | head -1
      register: worker_service
      changed_when: false

    - name: Discover worker buildarea path
      shell: systemctl show -p WorkingDirectory "{{ worker_service.stdout }}" | cut -d= -f2
      register: worker_path
      changed_when: false
      when: worker_service.stdout | length > 0

    - name: Stop the buildbot worker service
      service:
        name: "{{ worker_service.stdout }}"
        state: stopped
      when: worker_service.stdout | length > 0

    - name: Find the folders to remove and register them to a var
      find:
        paths: "{{ worker_path.stdout }}"
        file_type: any
        patterns: '3.*,pull_request*,custom*,twistd.log.*'
      register: cleanup
      when: worker_path.stdout is defined and worker_path.stdout | length > 0

    - name: Remove the files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ cleanup.files }}"
      loop_control:
        label: "{{ item.path }}"
      when: cleanup.files is defined

    - name: Start again the buildbot worker service
      service:
        name: "{{ worker_service.stdout }}"
        state: started
      when: worker_service.stdout | length > 0
